tests/test_wrapper.sh.in : Add 'set -e' so the script exits on error.

diff --git a/tests/test_wrapper.sh.in b/tests/test_wrapper.sh.in
--- a/tests/test_wrapper.sh.in
+++ b/tests/test_wrapper.sh.in
@@ -10,7 +10,10 @@ if [ ! -f sfversion@EXEEXT@ ]; then
 	fi
 
 sfversion=`./sfversion@EXEEXT@`
-	
+
+# Force exit on errors.
+set -e
+
 # generic-tests
 uname -a
 ./error_test@EXEEXT@
